name: nodir

networks:
    net:

services:
  nodir_project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodir_project
    restart: always
    networks:
      - net
    ports: 
      - 9004:9000